# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_OW', [dirname(__file__)])
        except ImportError:
            import _OW
            return _OW
        if fp is not None:
            try:
                _mod = imp.load_module('_OW', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _OW = swig_import_helper()
    del swig_import_helper
else:
    import _OW
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def version():
  return _OW.version()
version = _OW.version

def init(*args):
  return _OW.init(*args)
init = _OW.init

def get(*args):
  return _OW.get(*args)
get = _OW.get

def put(*args):
  return _OW.put(*args)
put = _OW.put

def finish():
  return _OW.finish()
finish = _OW.finish

def set_error_print(*args):
  return _OW.set_error_print(*args)
set_error_print = _OW.set_error_print

def get_error_print():
  return _OW.get_error_print()
get_error_print = _OW.get_error_print

def set_error_level(*args):
  return _OW.set_error_level(*args)
set_error_level = _OW.set_error_level

def get_error_level():
  return _OW.get_error_level()
get_error_level = _OW.get_error_level

def opt(*args):
  return _OW.opt(*args)
opt = _OW.opt
# This file is compatible with both classic and new-style classes.


