/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_OW_H
#define PHP_OW_H

extern zend_module_entry OW_module_entry;
#define phpext_OW_ptr &OW_module_entry

#ifdef PHP_WIN32
# define PHP_OW_API __declspec(dllexport)
#else
# define PHP_OW_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(OW);
PHP_MSHUTDOWN_FUNCTION(OW);
PHP_RINIT_FUNCTION(OW);
PHP_RSHUTDOWN_FUNCTION(OW);
PHP_MINFO_FUNCTION(OW);

ZEND_NAMED_FUNCTION(_wrap_version);
ZEND_NAMED_FUNCTION(_wrap_init);
ZEND_NAMED_FUNCTION(_wrap_get);
ZEND_NAMED_FUNCTION(_wrap_put);
ZEND_NAMED_FUNCTION(_wrap_finish);
ZEND_NAMED_FUNCTION(_wrap_set_error_print);
ZEND_NAMED_FUNCTION(_wrap_get_error_print);
ZEND_NAMED_FUNCTION(_wrap_set_error_level);
ZEND_NAMED_FUNCTION(_wrap_get_error_level);
ZEND_NAMED_FUNCTION(_wrap_opt);
#endif /* PHP_OW_H */
